//
// Exception.hpp
// mrlib
//
// Created by Matthew Remmel on 1/22/16.
// Copyright (c) 2015 Matthew Remmel. All rights reserved.

/*
 * The purpose of this class is to automate the printing of the stack trace
 * generated by using the StackTrace.hpp class. When this exception is thrown
 * it will automatically retrieve the stack trace and print it.
 */


#ifndef MRLIB_EXCEPTION_HPP
#define MRLIB_EXCEPTION_HPP

#include "StackTrace.hpp"
#include <exception>

namespace mrlib {

    class Exception : public std::exception {
    private:
        std::string _message;

    public:
        // Constructors
        Exception(const std::string& message);

        // String Representation
        std::string description() const;
        std::string inspect() const;

        // std::exception Override
        const char* what() const override ;
    };


    /////////////////////////////
    // TEMPLATE IMPLEMENTATION //
    /////////////////////////////

    // Constructors
    Exception::Exception(const std::string& message) {
        this->_message = message + "\nStack Trace:\n" + StackTrace::description();
    }

    // Object Override
    std::string Exception::description() const {
        return this->_message;
    }

    std::string Exception::inspect() const {
        return this->_message;
    }

    // std::exception Override
    const char* Exception::what() const {
        return this->_message.c_str();
    }
}

#endif // MRLIB_EXCEPTION_HPP
